---
# tasks file for rsyslog
- name: install rsyslog rsyslog-mysql
  yum: 
    name: '{{ item.name }}'
    state: '{{ item.state }}'
  with_items: 
    - { name: 'rsyslog', state: 'latest' }
    - { name: 'rsyslog-mysql', state: 'latest' }
    - { name: 'rsyslog-mysql', state: 'latest' }

- name: check PimpMyLog directory exists
  stat:
    path: /var/www/html/pimpmylog
  register: pimpmylog

- name: install PimpMyLog
  git:
    repo: 'https://github.com/potsky/PimpMyLog.git'
    dest: /var/www/html/pimpmylog
    clone: yes
    update: no
  when: not pimpmylog.stat.exists

- name: set time America/New_York php.ini
  lineinfile:
    path: /etc/php.ini
    regexp: '^;date.timezone ='
    line: 'date.timezone = America/New_York'

# - name: configure file permissions apache
#     file: 
#       dest:  /var/www/html/pimpmylog
#       owner: apache 
#       group: apache 
#       mode: 0775 
#       recurse: yes
    
# - name: configure directory permissions apache
#     file: 
#       dest:  /var/www/html/pimpmylog
#       owner: apache 
#       group: apache 
#       mode: 0775 
#       recurse: yes
    

# Restart Apache so that it recognizes the new module
- name: restart httpd
  service: 
    name: httpd
    state: restarted



#### Configure Rsyslog to output logs to Database.
# cat /usr/share/doc/rsyslog-8.24.0/mysql-createDB.sql | mysql -u root -p

# grant all privileges on Syslog.* to rsyslog@'localhost' identified by 'password';

# flush privileges; 

# exit

# # near line 22: add
# $ModLoad ommysql

# # for example, output logs for "authpriv.*"
# # how to wite ⇒ :ommysql:Host,DB,DBUser,DBPassword
# authpriv.*     :ommysql:localhost,Syslog,rsyslog,password

# systemctl restart rsyslog






# Resources: 
#https://blog.lysender.com/2015/07/centos-7-selinux-php-apache-cannot-writeaccess-file-no-matter-what/
# Ownership
# sudo chown apache:apache -R /data/www/html/sites/mysite
# cd /data/www/html/sites/mysite
 
# # File permissions, recursive
# find . -type f -exec chmod 0644 {} \;
 
# # Dir permissions, recursive
# find . -type d -exec chmod 0755 {} \;
 
# # SELinux serve files off Apache, resursive
# sudo chcon -t httpd_sys_content_t /data/www/html/sites/mysite -R
 
# # Allow write only to specific dirs
# sudo chcon -t httpd_sys_rw_content_t /data/www/html/sites/mysite/logs -R
# sudo chcon -t httpd_sys_rw_content_t /data/www/html/sites/mysite/uploads -R

# https://www.server-world.info/en/note?os=CentOS_7&p=rsyslog&f=2