---
# tasks file for glassFish
wget  http://download.oracle.com/glassfish/5.0/release/glassfish-5.0.zip

unzip glassfish-5.0.zip 

## not working 
ln -s /opt/glassfish5/bin/asadmin /usr/sbin/asadmin

## 

C:\Program Files\glassfish-3.0.1\glassfish\domains\domain1\config
Open domain.xml using any text editor.
Look for 8080 and change it to some other port number that doesn’t conflict with other port numbers.



 ./asadmin start-database --dbhome /home/castic/Documents/
 ./asadmin stop-database 


/var/www/html/glassfish5/bin

./asadmin start-domain

/var/www/html/glassfish5/glassfish/domains/domain1/config/admin-keyfile



- name: open 4848/tcp 8888/tcp and restart firewall
  firewalld:
    port: 4848/tcp
    permanent: true
    state: enabled
  with_items:
    - { port: '4848/tcp' , state: enabled}
    - { port: '8888/tcp' , state: enabled}
  notify:
    - reload firewall