---
# handlers file for webmin

- name: restart webmin
  service:
    name: "webmin"
    state: "restarted"

- name: enable webmin
  service:
    name: "webmin"
    enabled : yes

- name: reloaded firewall
  service: name=firewall state=reloaded