---
# tasks file for webmin

# - name: rpm_key add
#   rpm_key:
#     key : "{{ item.url }}"
#     state: "{{ item.state }}"
#   with_items:
#     - { state: "present", url: "http://www.webmin.com/jcameron-key.asc" }
#   tags: rpm_key add

# - name: import jcameron-key.asc
#   command: "{{ item }}"
#   warn: no
#   with_items:
#     - wget http://www.webmin.com/jcameron-key.asc
#     - rpm --import jcameron-key.asc

# - name: create webmin.repo 
#   template:
#     src={{ item.src }}
#     dest={{ item.dest }}
#     force=yes
#   with_items: 
#     - { src: 'webmin.repo', dest: '/etc/yum.repos.d/webmin.repo' }

- name: yum install usermin
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { state: "latest", name: "usermin" }
    - { state: "present", name: "perl-Digest-MD5" }
  notify: enable usermin
  tags: yum install

- name: replace in file
  replace:
    dest: "{{ item.dest }}"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  with_items:
    - { dest: "/etc/usermin/miniserv.conf", regexp: "^allow=.*$", replace: "allow={{ usermin_listen }}" }
    - { dest: "/etc/usermin/miniserv.conf", regexp: "^listen=.*$", replace: "listen={{ usermin_port }}" }
  notify: restart usermin
  tags: replace in file

  # Configuring Firewall Rules 
- name: open 20000/tcp and restart firewall
  firewalld:
    port: 20000/tcp
    permanent: true
    state: enabled

- name: reload firewall
  command: firewall-cmd --reload

# ADD THE FOLLOWING TO THE PATH 
#- name: start usermin
#  command: /etc/rc.d/init.d/usermin start








