---
# handlers file for webmin

- name: restart usermin
  service:
    name: "usermin"
    state: "restarted"

- name: enable usermin
  service:
    name: "usermin"
    enabled : yes

# - name: reloaded firewall
#   service: 
#     name: firewall-cmd 
#     state: reloaded