---
# tasks file for email
- name: install emailing service packages 
  yum: 
    name: '{{ item.name }}'
    state: '{{ item.state }}'
  with_items: 
    - { name: 'm4', state: 'latest' }
    - { name: 'sendmail-cf', state: 'latest' }
    - { name: 'sendmail', state: 'latest' }
    - { name: 'spamassassin', state: 'latest' }
    - { name: 'procmail', state: 'latest' }
    - { name: 'dovecot', state: 'latest' }

- name: add domain to sendmail.mc
  lineinfile:
    path: /etc/mail/sendmail.mc
    regexp: '^LOCAL_DOMAIN'
    line: "LOCAL_DOMAIN(`{{ localdomain }}')dnl"

- name: configure sendmail.mc and make sendmail.cf
  command: m4 /etc/mail/sendmail.mc /etc/mail/sendmail.cf
  register: m4_command_result
  ignore_errors: True

# - name: m4 command did not succeed
#   fail:
#     msg: "the m4 command failed"
#   when: "'m4_command_result.rc > 1"

- name: restart sendmail service
  service: 
    name: sendmail.service
    state: restarted
    enabled: yes 

- name: create .forward and .procmailrc file for users
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: 
    - { src: '.forward.j2', dest: '/root/.forward' }
    - { src: '.procmailrc', dest: '/root/.procmailrc'}

- name: configure file /etc/dovecot/dovecot.conf
  lineinfile:
    path: /etc/dovecot/dovecot.conf
    regexp: '^protocols ='
    line: "protocols = imap pop3 "

- name: configure file 20-pop3.conf pop3_uidl_format
  lineinfile:
    path: /etc/dovecot/conf.d/20-pop3.conf
    regexp: '^pop3_uidl_format'
    line: "pop3_uidl_format = %08Xu%08Xv"

- name: configure file 20-pop3.conf pop3_client_workarounds
  lineinfile:
    path: /etc/dovecot/conf.d/20-pop3.conf
    regexp: '^pop3_client_workarounds'
    line: "pop3_client_workarounds = outlook-no-nuls oe-ns-eoh"

- name: restart dovecot service
  service: 
    name: dovecot.service
    state: restarted
    enabled: yes 

# - name: open imap and pop3 ports
#   firewalld:
#     zone:  public
#     service: "{{ item.service }}"
#     port: "{{ item.port }}"
#     permanent: true
#     immediate: true
#     state: enabled
#   with_items:
#     - { service: 'pop3', port: '110/tcp' }
#     - { service: 'imap', port: '143/tcp'}


- name: open imap and pop3 ports
  firewalld:
    zone:  public
    port: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - 110/tcp
    - 143/tcp


- name: open imap and pop3 service
  firewalld:
    zone:  public
    service: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - imap
    - pop3

- name: restart spamassassin service
  service: 
    name: spamassassin.service
    state: restarted
    enabled: yes 

- name: reload firewall
  command: firewall-cmd --reload 


# Resources: 
# https://www.jeffgeerling.com/blogs/jeff-geerling/configure-sendmail-centos
# https://tecadmin.net/install-sendmail-server-on-centos-rhel-server/

# https://www.centos.org/docs/5/html/5.1/Deployment_Guide/s3-email-mta-sendmail-changes.html

# How do I ensure that procmail is working
# How do I use SpamAssassin with procmail
# https://wiki.apache.org/spamassassin/UsedViaProcmail

# https://major.io/2008/08/13/basic-procmail-configuration-with-spamassassin-filtering/

# https://www.cs.rutgers.edu/~watrous/procmail-spam.html

# https://svn.apache.org/repos/asf/spamassassin/trunk/procmailrc.example


# Send Mail
# mail [user]@[server hostname]
#ctl-D -> to exit prompt


# Sample recipes procmail 
# https://www.cs.rutgers.edu/~watrous/procmail-spam.html