---
# tasks file for bacula
- name: install the bacula 
  yum: 
    name: '{{ item.name }}'
    state: '{{ item.state }}'
  with_items: 
    - { name: 'bacula-director', state: 'latest' }
    - { name: 'bacula-storage', state: 'latest' }
    - { name: 'bacula-console', state: 'latest' }
    - { name: 'bacula-client', state: 'latest' }
    - { name: 'bacula-storage-mysql', state: 'latest' }
    - { name: 'bacula-client', state: 'latest' }
    - { name: 'bacula-client', state: 'latest' }






# Resources: 
#https://www.digitalocean.com/community/tutorials/how-to-install-bacula-server-on-centos-7
#https://blog.bacula.org/whitepapers/CommunityInstallationGuide.pdf
### THIS WORKS 
# http://www.chriscouture.com/installing-bacula-webmin-bacula-webon-centos-7/
# WEB GUI
# http://docs.bacula-web.org/en/v8.0.1/02_install/requirements.html#install-requirements